### ISSUE TITLE
Graphic clock offset does not apply

### ISSUE THREAD

**Issue by IniGisah** [albertstarfield/nvidiaHeadlessControl#1]
I think coolbits value doesn't applied to my system. There is no clock offset settings on my nvidia-settings app.

Here's my specs
Pop OS 22.04
NVIDIA GeForce GTX 660 with Nvidia 470.141.03 driver version
Kernel : Linux pop-os 6.0.8-x64v2-xanmod1 

logs on folder
[nvidiafbcoolbitHack.log](https://github.com/albertstarfield/nvidiaHeadlessControl/files/10019196/nvidiafbcoolbitHack.log)

Xorg logs, maybe this can help
[Xorg.420.log](https://github.com/albertstarfield/nvidiaHeadlessControl/files/10019297/Xorg.420.log)

**Comment by albertstarfield** [comment]
Thank you for the report. After I checked the logs that you gave me, it seems there is a PCI bus (The configuration seems to select 1:0:0 instead of 7:0:0 which is your GPU configuration) mismatch caused the Nvidia driver to be confused and spit out device not found (See Xorg.420.log) and alas lead to display not found at nvidiafbcoolbitHack.log which end up nvidia-settings not end up applying any configuration that you've set.
New update will be pushed ASAP fixing the issue

**Comment by IniGisah** [comment]
Nice, now working properly after latest update, thank you
